### ISSUE TITLE
Channel User List Bug

### ISSUE THREAD

**Issue by TheDetectiveTaco** [BurdIRC/burd#16]
Randomly the user list duplicates everyone's nick like 4 times and shows everyone's nick 4 times each instead of once. Sometimes it even adds users from channels on other networks into the list. I remember having the user list show each persons nick 4 times each and have nicks from #homescreen on Rizon show up in ##chats on Freenode.

**Comment by TheDetectiveTaco** [comment]
Will be fixed in next version hopefully

**Comment by haxednet** [comment]
I believe this may be due to a shared cache object. when names come in they are stored in a cache _until end of names_. This works fine on a single server because you can only join one channel at a time, however the cache was mistakenly shared between all servers, so if you join two channels on different networks at the same time it could corrupt the cache.

I have since resolved this cache issue and I'm uploading updated code now. Try running the source from github and let me know if this is still happening.

**Comment by haxednet** [comment]
Turns out the cache bug was not causing this problem so we'll have to dig deeper. I suspect the issue might be NAMES reply not being orderly from the server. I have updated the code again so try running the updated source and let me know if you still have this issue.

**Comment by TheDetectiveTaco** [comment]
Issue fixed. Issue was is fixed in Burd IRC 0.6.2 Release Candidate 2. https://github.com/BurdIRC/burd/releases/tag/0.6.2-rc2
